### ISSUE TITLE
Built project artifacts in source control not a good idea

### ISSUE THREAD

**Issue by DavidWhitlock** [alexander94dmitriev/WebImageCollector#1]
Hey, @alexander94dmitriev.

I recommend against committing (class/jar/war/IntelliJ) files to GItHub that are derived from project source.  There are a couple of reasons that this is not a good idea:
   * It makes your "source code" repository bigger.  Tools like git are not optimized for large files (especially large binary files) and it takes up more room when the repository is cloned.
   * It can become cumbersome to keep the source code and committed artifacts in sync.  If the only way to get the artifacts is to check them out of version control, then you'll be forced to build the artifacts and commit them whenever you commit a code change.
   * While it might not be a huge problem with Java code, it's probably not a good idea for people to share binary files built on different development machines.  If there is any native code that gets check it, it won't be sharable if you're on Windows and I'm on a Mac.

I thought this article offered some interesting conversation on the topic: https://www.quora.com/Should-binary-files-be-stored-in-a-Git-repository

So, I recommend that you remove the files in the "out" directory and the ".idea" directories from the repository.

**Comment by DavidWhitlock** [comment]
When you added the Maven project for #2, you committed your "target" file.  😄 

Please remove that directory.  I recommend that you add the target directory to the `.gitignore` file for this repository.

**Comment by alex94dmit** [comment]
Oops! My bad, forgot about this one!
