### ISSUE TITLE
Images should be stored in a location that is not platform specific

### ISSUE THREAD

**Issue by DavidWhitlock** [alexander94dmitriev/WebImageCollector#3]
Hey, @alexander94dmitriev.  I took a look at the most recent code and the UI looks pretty good.  When I attempted to add some images, nothing appeared to happen in the UI and there was a big ugly stack trace in the server log.

```
java.io.IOException: File not found
	at controller.ImageService.initializeImageList(ImageService.java:36)
	at view.BasicView.uploadFile(BasicView.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.el.parser.AstValue.invoke(AstValue.java:247)
	at org.apache.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:267)
	at com.sun.faces.facelets.el.TagMethodExpression.invoke(TagMethodExpression.java:105)
	at org.primefaces.component.fileupload.FileUpload.broadcast(FileUpload.java:319)
	at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:755)
	at javax.faces.component.UIViewRoot.processDecodes(UIViewRoot.java:931)
	at com.sun.faces.lifecycle.ApplyRequestValuesPhase.execute(ApplyRequestValuesPhase.java:78)
	at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
	at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:198)
	at javax.faces.webapp.FacesServlet.service(FacesServlet.java:658)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:830)
```

This wasn't surprising, though.  As you pointed out, the location of the image files is hard-coded to `c:/images/images` which isn't going to work on my Mac.

Let's figure out how to fix this.  How about instead of hard-coding it, the application can store the images in a file named `images` in the user's home directory?

**Comment by alex94dmit** [comment]
Sounds like a good option. However, I'm not familiar what's the path to user's home directory in Mac. I assume on windows it will be _c:/users_

**Comment by alex94dmit** [comment]
I wonder if we can try out this
https://stackoverflow.com/questions/11113974/what-is-the-cross-platform-way-of-obtaining-the-path-to-the-local-application-da

**Comment by DavidWhitlock** [comment]
That might work.  Just using `System.getProperty("user.home")` might be sufficient, also.

**Comment by alex94dmit** [comment]
David, I'm just made a changes to the project, so that it uses user home directory. For me it's a _c:/users/user_name_, for you it should be _/home/user_name_ I assume. It should create an _image_ folder where you can upload images in. Give it a try now, I hope it should work.

**Comment by DavidWhitlock** [comment]
Hey, @alexander94dmitriev.  I got the latest code and I can now upload images.  Sweet!  I'm still seeing that stack trace, though.  It was accompanied by this message:

```
Something went wrong working with input/output streams in FileServlet:/Users/david/images/ (Is a directory)
```

I also tried a couple of other pieces of functionality like adding tags and creating collections.  I saw some things that there were a little surprising, but I'm not sure what to expect.

I recommend that we come up with some descriptions for the behavior of the system.  I suggest that you use the "given/when/then" format: https://martinfowler.com/bliki/GivenWhenThen.html

**Comment by alex94dmit** [comment]
This is the issue I'm still wasn't able to solve. It seems that FileServlet is called once more after the images are loaded, but there's actually no file in the responce, so I'm not sure what's wrong with it.

I believe what I'm going to do is to add a messages after the specific action was taken, like "Image is uplaoded", "Collection is created" etc.
As of the description... Do you mean that this should be added as a documentation for methods?

**Comment by DavidWhitlock** [comment]
Yeah.  I recommend adding logging to the FileServlet to figure out what's going on.  You might also want to attach with a debugger to figure out it.

With regards to the given/when/then scenarios, I'm not sure about the best place to document that.  You could create a wiki page on GitHub.  You could also check in a markdown file.  That might allow us to have a better conversation about the scenarios.  Make sense?

**Comment by alex94dmit** [comment]
Pretty much, what you mean is that I should document the features separatelly so you can better understand the functionality of the project, is that correct?

**Comment by DavidWhitlock** [comment]
Yes.  That is a good way to put it.  How about you capture them in the README.md for the project?  That will make it nice and visible.  We can always move it someplace else later.

**Comment by alex94dmit** [comment]
I figured that the problem with the message about the IO streams is that at some moment the FileServlet is called to process the directory itself. So the method just gonna stop when it will figure out that the current file is just a directory.

I started to add the features to the Readme.MD

**Comment by DavidWhitlock** [comment]
Thanks, Alex.  I think we're done with this issue.
