### ISSUE TITLE
Three images uploaded, but the same image is displayed three times

### ISSUE THREAD

**Issue by DavidWhitlock** [alexander94dmitriev/WebImageCollector#4]
* Given:
      * The images directory does not exist (`rm -rf ~/images`)
      * The WebImageCollector is running (`mvn clean jetty:run-war`)
   * When:
      * I click the "Choose" button and select three image files to upload
   * Expected:
      * Each image is displayed in the "Images" table
   * Actual:
      * One image is displayed three times

<img width="1125" alt="screen shot 2017-11-07 at 5 18 13 am" src="https://user-images.githubusercontent.com/2935912/32495583-1b763db8-c37b-11e7-8b3d-6e37c9e2d9c6.png">

I saw this exception in the Jetty output:

```
java.io.IOException: File not found
	at controller.ImageService.initializeImageList(ImageService.java:36)
	at view.BasicView.init(BasicView.java:50)
```

and this message:

```
Something went wrong working with input/output streams in FileServlet:/Users/david/images/ (Is a directory)
```

**Comment by alex94dmit** [comment]
Hm, interesting, I didn't have that case before. I'm gonna take a look at it later today. If you highlight all of the images, do they have the same name?

The last message is most likely connected to the first issue, but I believe the second one happens because it tries to read imageData.txt which contains the info about preuploaded images. It's weird, though, since war should have it. But I'll make a check in case if it doesn't exist.

**Comment by alex94dmit** [comment]
I have added a fix for missing a File, please pull the changes.

However, I cannot replicate the problem with having 3 identical images in the table. Maybe doing a fresh pull and clean should do its thing...

**Comment by DavidWhitlock** [comment]
Interesting.  Yesterday, I was able to upload JPEG files.  Today, I see this error message:

![image](https://user-images.githubusercontent.com/2935912/32551115-4dab1f8c-c444-11e7-94c8-3c0b16e4df47.png)

That's cool.

I located some PNGs on my laptop (I have no idea who these people are 😄 ), selected three files, and it looks like they were included twice:

![image](https://user-images.githubusercontent.com/2935912/32551381-2ec2441e-c445-11e7-9d29-2f3a62f8c84c.png)

**Comment by alex94dmit** [comment]
That's ood because since the previous week I intentionally added the limitation on file extensions being able to upload. So you should only be able to use PNG. At least for now, the frameworks seems to have a problems with JPG.

Hmmmmmm... Did you try to include them separatelly, one-by-one?

**Comment by DavidWhitlock** [comment]
If I add them one-by-one, it worked as I'd expect.  After adding two images individually, I added two images in the same upload and it worked as expected.

When I start over clean (that is, after deleting the `images` directory) and add three image in the same upload, I still see multiple copies of the same image.

Have you been able to replicate the behavior in this issue?

**Comment by alex94dmit** [comment]
Hm, no, I still don't have any issues like this one.

Did you check if there're actual duplicates in the folder?

I think I can limit the addition of image in case if it already exists in the list, though technically it doesn't solve the problem, it seems a stream issue.

**Comment by alex94dmit** [comment]
I have added some fixes to the project. I wonder if it will help to our situation.

**Comment by DavidWhitlock** [comment]
Hey, @alexander94dmitriev.  I'm still seeing the same behavior when I upload multiple images after deleting the `~/images` directory.

Are you able to reproduce this behavior when you select multiple PNG files in the upload dialog?

![image](https://user-images.githubusercontent.com/2935912/32981967-62d4b11c-cc31-11e7-998d-94ff7cde7112.png)

**Comment by alex94dmit** [comment]
No, still without any success on reproducing this.

I believe the only way to fix it is to restrict the upload with a single file only.

**Comment by alex94dmit** [comment]
I have locked the multifile upload feature.
